name: mobile_clean_check
description: "mobile_clean_check"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  bloc: ^8.1.4
  dio: ^5.7.0
  shared_preferences: ^2.3.2
  intl: ^0.19.0
  image_picker: ^1.1.2
  flutter_slidable: ^3.1.1
  flutter_sticky_header: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: Jost
      fonts:
        - asset: assets/fonts/Jost-Bold.ttf
          weight: 700
        - asset: assets/fonts/Jost-Medium.ttf
          weight: 500
        - asset: assets/fonts/Jost-Regular.ttf
          weight: 400
